DROP TABLE "user_auth_tokens";--> statement-breakpoint
DROP TABLE "user_followed_artists";--> statement-breakpoint
DROP TABLE "user_music_preferences";--> statement-breakpoint
DROP TABLE "venue_insider_tips";--> statement-breakpoint
DROP TABLE "venue_photos";--> statement-breakpoint
DROP TABLE "venue_reviews";--> statement-breakpoint
DROP TABLE "user_follows_artists";--> statement-breakpoint
DROP TABLE "admin_notifications";--> statement-breakpoint
DROP TABLE "content_moderation";--> statement-breakpoint
DROP TABLE "data_backups";--> statement-breakpoint
DROP TABLE "moderation_logs";--> statement-breakpoint
DROP TABLE "platform_stats";--> statement-breakpoint
DROP TABLE "reports";--> statement-breakpoint
DROP TABLE "system_health";--> statement-breakpoint
DROP TABLE "user_activity_log";--> statement-breakpoint
DROP TABLE "artist_followers";--> statement-breakpoint
DROP TABLE "popular_searches";--> statement-breakpoint
DROP TABLE "saved_searches";--> statement-breakpoint
DROP TABLE "search_analytics";--> statement-breakpoint
DROP TABLE "user_bans";--> statement-breakpoint
DROP TABLE "anomalies";--> statement-breakpoint
DROP TABLE "artist_analytics";--> statement-breakpoint
DROP TABLE "data_quality_checks";--> statement-breakpoint
DROP TABLE "events";--> statement-breakpoint
DROP TABLE "experiment_assignments";--> statement-breakpoint
DROP TABLE "experiment_results";--> statement-breakpoint
DROP TABLE "experiments";--> statement-breakpoint
DROP TABLE "page_view_stats";--> statement-breakpoint
DROP TABLE "realtime_analytics";--> statement-breakpoint
DROP TABLE "show_analytics";--> statement-breakpoint
DROP TABLE "user_recommendations";--> statement-breakpoint
DROP TABLE "user_sessions";--> statement-breakpoint
DROP TABLE "artist_update_subscriptions";--> statement-breakpoint
DROP TABLE "digest_content";--> statement-breakpoint
DROP TABLE "email_batches";--> statement-breakpoint
DROP TABLE "email_engagement";--> statement-breakpoint
DROP TABLE "email_queue_enhanced";--> statement-breakpoint
DROP TABLE "email_templates";--> statement-breakpoint
DROP TABLE "notification_categories";--> statement-breakpoint
DROP TABLE "show_reminder_subscriptions";--> statement-breakpoint
DROP TABLE "transactional_emails";--> statement-breakpoint
DROP TABLE "user_notification_preferences";--> statement-breakpoint
DROP TABLE "aggregated_metrics";--> statement-breakpoint
DROP TABLE "data_lineage";--> statement-breakpoint
DROP TABLE "data_quality_metrics";--> statement-breakpoint
DROP TABLE "data_retention_policies";--> statement-breakpoint
DROP TABLE "data_sources";--> statement-breakpoint
DROP TABLE "dim_date";--> statement-breakpoint
DROP TABLE "etl_job_runs";--> statement-breakpoint
DROP TABLE "etl_jobs";--> statement-breakpoint
DROP TABLE "fact_events";--> statement-breakpoint
DROP TABLE "materialized_views";--> statement-breakpoint
DROP TABLE "stream_checkpoints";--> statement-breakpoint
DROP TABLE "rate_limits";--> statement-breakpoint
DROP TABLE "api_keys";--> statement-breakpoint
DROP TABLE "sync_jobs";--> statement-breakpoint
DROP TABLE "sync_progress";