#!/bin/bash

# Emergency Vercel Deployment Script
# Since theset.live is pointing to Lovable.app, we'll deploy to Vercel with a different URL

echo "🚨 CRITICAL DEPLOYMENT ISSUE DETECTED"
echo "====================================="
echo "❌ theset.live is pointing to a LOVABLE.APP deployment"
echo "❌ Your Next.js app is NOT deployed there"
echo ""
echo "🔧 SOLUTION: Deploy to Vercel with automatic URL"
echo ""

# Check if we're in the right directory
if [ ! -f "package.json" ]; then
    echo "❌ Error: Not in project root directory"
    exit 1
fi

echo "📦 Project: mysetlist-s4"
echo "📁 GitHub: https://github.com/swbam/mysetlist-s4"
echo ""

echo "🚀 DEPLOYMENT OPTIONS:"
echo "======================"
echo ""
echo "OPTION 1: Deploy via Vercel Dashboard (RECOMMENDED)"
echo "----------------------------------------------------"
echo "1. Go to: https://vercel.com/new"
echo "2. Import from GitHub: swbam/mysetlist-s4"
echo "3. Select 'main' branch"
echo "4. Framework Preset: Next.js"
echo "5. Root Directory: ./"
echo "6. Build Command: pnpm build"
echo "7. Output Directory: apps/web/.next"
echo "8. Install Command: pnpm install --frozen-lockfile"
echo ""
echo "OPTION 2: Deploy via Vercel CLI"
echo "--------------------------------"
echo "Run these commands:"
echo ""
echo "  # Install Vercel CLI if needed"
echo "  npm i -g vercel"
echo ""
echo "  # Link to a NEW Vercel project"
echo "  vercel link"
echo "  # Choose: Create new project"
echo "  # Name it: mysetlist-next"
echo ""
echo "  # Deploy to production"
echo "  vercel --prod"
echo ""
echo "Your app will be available at:"
echo "  https://mysetlist-next.vercel.app"
echo ""
echo "OPTION 3: Use GitHub Integration"
echo "---------------------------------"
echo "1. Push this repo to GitHub ✅ (already done)"
echo "2. Go to: https://vercel.com/import/git"
echo "3. Import: https://github.com/swbam/mysetlist-s4"
echo "4. It will auto-deploy on every push to main"
echo ""
echo "🔐 ENVIRONMENT VARIABLES TO ADD IN VERCEL:"
echo "==========================================="
echo "Copy from: VERCEL_ENV_VARIABLES.txt"
echo ""
echo "Critical ones:"
echo "  - DATABASE_URL"
echo "  - NEXT_PUBLIC_SUPABASE_URL"
echo "  - NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo "  - SUPABASE_SERVICE_ROLE_KEY"
echo "  - SPOTIFY_CLIENT_ID"
echo "  - SPOTIFY_CLIENT_SECRET"
echo "  - TICKETMASTER_API_KEY"
echo ""
echo "⚠️  IMPORTANT NOTES:"
echo "===================="
echo "1. theset.live domain is occupied by Lovable.app"
echo "2. You'll get a new URL like: mysetlist-[random].vercel.app"
echo "3. You can add custom domain later in Vercel settings"
echo "4. The background sync system will work on the new URL"
echo ""
echo "Press Enter to continue..."
read

echo ""
echo "🎯 Quick Deploy Command (if Vercel CLI is installed):"
echo "======================================================"
echo ""
echo "vercel --prod --yes --name mysetlist-production"
echo ""
echo "This will:"
echo "- Deploy immediately"
echo "- Create a new project"
echo "- Give you a production URL"
echo ""