name: Accessibility Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  a11y:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Start application
        run: |
          npm run start &
          npx wait-on http://localhost:3001 -t 30000
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

      - name: Run axe accessibility tests
        run: |
          npm install -g @axe-core/cli
          axe http://localhost:3001 --tags wcag2a,wcag2aa,wcag21a,wcag21aa --exit

      - name: Run Pa11y tests
        run: |
          npm install -g pa11y
          pa11y http://localhost:3001 --standard WCAG2AA
          pa11y http://localhost:3001/trending --standard WCAG2AA
          pa11y http://localhost:3001/artists --standard WCAG2AA

      - name: Generate accessibility report
        if: failure()
        run: |
          mkdir -p accessibility-reports
          pa11y http://localhost:3001 --reporter html > accessibility-reports/home.html
          pa11y http://localhost:3001/trending --reporter html > accessibility-reports/trending.html
          pa11y http://localhost:3001/artists --reporter html > accessibility-reports/artists.html

      - name: Upload accessibility reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: accessibility-reports
          path: accessibility-reports/
          retention-days: 7

      - name: Comment PR with results
        if: github.event_name == 'pull_request' && failure()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: accessibility
          message: |
            ## ♿ Accessibility Issues Found
            
            WCAG 2.1 AA compliance issues detected. Please review the uploaded accessibility reports.
            
            Common issues to check:
            - Color contrast ratios
            - Missing alt text
            - Keyboard navigation
            - ARIA labels
            - Form labels